#!/usr/bin/env bash
# kids-control — install the protections on the child's computer.
# Usage: sudo ./install.sh
# Idempotent: edit the lists in config/ and re-run.
#
# Test mode (development): KIDS_CONTROL_ROOT=/tmp/testroot ./install.sh
#   → writes under that prefix and skips system actions (apt, NetworkManager).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="$SCRIPT_DIR/config"
ROOT="${KIDS_CONTROL_ROOT:-}"

MARK_BEGIN="# BEGIN kids_control"
MARK_END="# END kids_control"

HOSTS_FILE="$ROOT/etc/hosts"
POLICY_PATHS=("$ROOT/etc/firefox/policies/policies.json" "$ROOT/usr/lib/firefox/distribution/policies.json")
UBLOCK_MANAGED="$ROOT/usr/lib/mozilla/managed-storage/uBlock0@raymondhill.net.json"
NM_DNS_CONF="$ROOT/etc/NetworkManager/conf.d/90-kids-control-dns.conf"
RESOLVED_CONF="$ROOT/etc/systemd/resolved.conf.d/90-kids-control-dns.conf"

ALT_BROWSERS=(chromium chromium-browser brave-browser google-chrome-stable
              epiphany-browser falkon midori konqueror opera-stable
              vivaldi-stable microsoft-edge-stable)

info(){ printf '\033[1;34m[kids-control]\033[0m %s\n' "$*"; }
warn(){ printf '\033[1;33m[kids-control]\033[0m %s\n' "$*"; }

# ─── Preflight ───────────────────────────────────────────────────────────
if [ -z "$ROOT" ] && [ "$(id -u)" -ne 0 ]; then
  echo "This script must be run with sudo." >&2
  exit 1
fi
command -v python3 >/dev/null || { echo "python3 is required." >&2; exit 1; }
if [ -z "$ROOT" ] && ! command -v firefox >/dev/null; then
  warn "Firefox not found in PATH — policies will be installed anyway."
fi
for f in blocked-domains.txt blocked-url-patterns.txt safesearch-hosts.txt \
         firefox-policies.template.json ublock-managed.json; do
  [ -f "$CONFIG_DIR/$f" ] || { echo "Missing file: config/$f" >&2; exit 1; }
done

# ─── 1. Firefox policies (system-wide, not editable without root) ───────
info "Generating Firefox policies and uBlock settings…"
GEN_DIR="$(mktemp -d)"
python3 - "$CONFIG_DIR" "$GEN_DIR" <<'PYEOF'
import json, sys, pathlib
cfg = pathlib.Path(sys.argv[1])
out = pathlib.Path(sys.argv[2])

def lines(name):
    p = cfg / name
    if not p.is_file():
        return []
    return [l.strip() for l in p.read_text(encoding="utf-8").splitlines()
            if l.strip() and not l.strip().startswith("#")]

channels = lines("blocked-channels.txt")
handles  = [c for c in channels if c.startswith("@")]
for bad in (c for c in channels if not c.startswith("@")):
    print(f"kids-control: ignored entry in blocked-channels.txt (must start with @): {bad}", file=sys.stderr)

# --- Firefox policies ---
policies = json.loads((cfg / "firefox-policies.template.json").read_text(encoding="utf-8"))
block = []
for d in lines("blocked-domains.txt"):
    block += [f"*://{d}/*", f"*://*.{d}/*"]
block += lines("blocked-url-patterns.txt")
for h in handles:
    block += [f"*://www.youtube.com/{h}*", f"*://m.youtube.com/{h}*"]
policies["policies"]["WebsiteFilter"]["Block"] = block
(out / "policies.json").write_text(json.dumps(policies, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

# --- uBlock managed storage (template + blocked channels/keywords) ---
ub = json.loads((cfg / "ublock-managed.json").read_text(encoding="utf-8"))
filters = ub["data"]["toOverwrite"]["filters"]
CONTAINERS = ["ytd-rich-item-renderer", "ytd-video-renderer", "ytd-compact-video-renderer",
              "yt-lockup-view-model", "ytd-channel-renderer", "ytm-shorts-lockup-view-model"]
if handles:
    filters.append("! kids-control: blocked channels (from blocked-channels.txt)")
    for h in handles:
        filters.append(f'www.youtube.com##a[href^="/{h}"]')
        for c in CONTAINERS:
            filters.append(f'www.youtube.com##{c}:has(a[href^="/{h}"])')
(out / "ublock.json").write_text(json.dumps(ub, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
PYEOF
GENERATED="$GEN_DIR/policies.json"

for dest in "${POLICY_PATHS[@]}"; do
  install -d "$(dirname "$dest")"
  if [ -f "$dest" ] && ! grep -q kids.control "$dest" && [ ! -f "$dest.kids_control.bak" ]; then
    cp -a "$dest" "$dest.kids_control.bak"
    warn "Existing policies.json backed up: $dest.kids_control.bak (merge by hand if needed)"
  fi
  install -m 644 "$GENERATED" "$dest"
  info "Policies written: $dest"
done
# ─── 2. Managed uBlock Origin settings (Shorts + blocked channels) ──────
install -d "$(dirname "$UBLOCK_MANAGED")"
install -m 644 "$GEN_DIR/ublock.json" "$UBLOCK_MANAGED"
info "Managed uBlock Origin settings: $UBLOCK_MANAGED"
rm -rf "$GEN_DIR"

# ─── 3. /etc/hosts (blocks in every app + forces SafeSearch) ────────────
info "Updating $HOSTS_FILE…"
TMP_HOSTS="$(mktemp)"
if [ -f "$HOSTS_FILE" ]; then
  sed "/^${MARK_BEGIN}\$/,/^${MARK_END}\$/d" "$HOSTS_FILE" > "$TMP_HOSTS"
else
  install -d "$(dirname "$HOSTS_FILE")"
  : > "$TMP_HOSTS"
fi
{
  echo "$MARK_BEGIN"
  echo "# Generated by kids-control — do not edit this block (re-run install.sh)"
  while IFS= read -r d; do
    case "$d" in ''|\#*) continue ;; esac
    printf '0.0.0.0 %s\n' "$d"
  done < "$CONFIG_DIR/blocked-domains.txt"
  grep -Ev '^[[:space:]]*(#|$)' "$CONFIG_DIR/safesearch-hosts.txt"
  echo "$MARK_END"
} >> "$TMP_HOSTS"
install -m 644 "$TMP_HOSTS" "$HOSTS_FILE"
rm -f "$TMP_HOSTS"
info "kids-control block injected into $HOSTS_FILE"

# ─── 4. Family DNS (Cloudflare Family: adult content + malware) ─────────
# On systemd-resolved systems, NetworkManager's [global-dns-domain-*] never
# reaches resolved and leaves the machine without working DNS — configure
# resolved directly there; keep the NM drop-in only for the other systems.
USE_RESOLVED=no
if [ -n "$ROOT" ]; then
  USE_RESOLVED="${KIDS_CONTROL_DNS_RESOLVED:-no}"
elif systemctl is-active --quiet systemd-resolved; then
  USE_RESOLVED=yes
fi
if [ "$USE_RESOLVED" = yes ]; then
  install -d "$(dirname "$RESOLVED_CONF")"
  cat > "$RESOLVED_CONF" <<'EOF'
# Generated by kids-control: Cloudflare Family DNS (blocks adult content + malware)
[Resolve]
DNS=1.1.1.3 1.0.0.3 2606:4700:4700::1113 2606:4700:4700::1003
Domains=~.
EOF
  rm -f "$NM_DNS_CONF"
  info "Family DNS configured (systemd-resolved): $RESOLVED_CONF"
  if [ -z "$ROOT" ]; then
    systemctl restart systemd-resolved
  fi
else
  install -d "$(dirname "$NM_DNS_CONF")"
  cat > "$NM_DNS_CONF" <<'EOF'
# Generated by kids-control: Cloudflare Family DNS (blocks adult content + malware)
[global-dns-domain-*]
servers=1.1.1.3,1.0.0.3,2606:4700:4700::1113,2606:4700:4700::1003
EOF
  rm -f "$RESOLVED_CONF"
  info "Family DNS configured (NetworkManager): $NM_DNS_CONF"
  if [ -z "$ROOT" ]; then
    if systemctl is-active --quiet NetworkManager; then
      systemctl reload NetworkManager 2>/dev/null || systemctl restart NetworkManager
    fi
  fi
fi
if [ -z "$ROOT" ]; then
  resolvectl flush-caches 2>/dev/null || true
fi

# ─── 5. Screen time: Timekpr-nExT ───────────────────────────────────────
if [ -z "$ROOT" ]; then
  if ! dpkg -s timekpr-next >/dev/null 2>&1; then
    info "Installing Timekpr-nExT (screen time)…"
    apt-get install -y timekpr-next || warn "Failed to install timekpr-next — install it manually."
  else
    info "Timekpr-nExT already installed."
  fi
fi

# ─── 6. Hardening: alternative browsers + flatpak ───────────────────────
if [ -z "$ROOT" ]; then
  for pkg in "${ALT_BROWSERS[@]}"; do
    if dpkg -s "$pkg" >/dev/null 2>&1; then
      warn "Removing alternative browser: $pkg"
      apt-get remove -y "$pkg"
    fi
  done
  if dpkg -s flatpak >/dev/null 2>&1; then
    warn "Removing flatpak (prevents installing browsers without sudo)."
    warn "Note: may also remove the Software Manager (mintinstall) — reversible, see README."
    apt-get remove -y flatpak || warn "Failed to remove flatpak — see README."
  fi
fi

# ─── Summary ────────────────────────────────────────────────────────────
echo
info "Install complete. Active protections:"
info "  1. Firefox: TikTok & friends blocked, YouTube Shorts blocked, uBlock forced,"
info "     DoH locked, about:config blocked, homepage = Qwant Junior."
info "  2. /etc/hosts: TikTok/social networks blocked everywhere,"
info "     Google SafeSearch + YouTube Restricted Mode forced."
info "  3. Cloudflare Family DNS (1.1.1.3): adult content blocked."
info "  4. Timekpr-nExT: set limits via 'Timekpr-nExT (administration)'."
info "Restart Firefox (ideally the whole session) to apply everything."
info "Checks: see README.md, 'Verify' section."
